services:
  - type: web
    name: browserunblocked
    env: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: CHROME_HOME
        value: https://www.google.com
      - key: VIEWPORT_WIDTH
        value: 1152
      - key: VIEWPORT_HEIGHT
        value: 648
      - key: FRAME_QUALITY
        value: 42
      - key: IDLE_MINUTES
        value: 6
